CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                   NVARCHAR (450)     NOT NULL,
    [UserName]             NVARCHAR (256)     NULL,
    [NormalizedUserName]   NVARCHAR (256)     NULL,
    [Email]                NVARCHAR (256)     NULL,
    [NormalizedEmail]      NVARCHAR (256)     NULL,
    [EmailConfirmed]       BIT                NOT NULL,
    [PasswordHash]         NVARCHAR (MAX)     NULL,
    [SecurityStamp]        NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]     NVARCHAR (MAX)     NULL,
    [PhoneNumber]          NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed] BIT                NOT NULL,
    [TwoFactorEnabled]     BIT                NOT NULL,
    [LockoutEnd]           DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]       BIT                NOT NULL,
    [AccessFailedCount]    INT                NOT NULL,
    [FirstName]            VARCHAR (50)       NULL,
    [LastName]             VARCHAR (50)       NULL,
    [Status]               BIT                NOT NULL,
    [UpdatedAt]            DATETIME2 (3)      NULL,
    [DisplayName]          VARCHAR (30)       NULL,
    [UserId]               NVARCHAR (450)     NULL,
    [Address]              VARCHAR (200)      NULL,
    [CreatedBy]            NVARCHAR (450)     NULL,
    [CreatedAt]            DATETIME2 (3)      NOT NULL,
    [IsSuperAdmin]         BIT                NOT NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);

