CREATE TABLE [dbo].[Customer] (
    [Id]                 NVARCHAR (450) NOT NULL,
    [TenantId]           INT            NOT NULL,
    [Title]              VARCHAR (50)   NULL,
    [FirstName]          VARCHAR (50)   NULL,
    [MiddleName]         VARCHAR (50)   NULL,
    [LastName]           VARCHAR (50)   NULL,
    [CountryCode]        VARCHAR (50)   NULL,
    [Email]              VARCHAR (50)   NULL,
    [MobileNumber]       VARCHAR (50)   NULL,
    [Street]             VARCHAR (50)   NULL,
    [City]               VARCHAR (50)   NULL,
    [PostCode]           VARCHAR (50)   NULL,
    [Gender]             VARCHAR (50)   NULL,
    [DOB]                DATETIME2 (3)  NOT NULL,
    [IdType]             INT            NOT NULL,
    [IdNumber]           VARCHAR (50)   NULL,
    [IdExpiryDate]       DATETIME2 (3)  NOT NULL,
    [Status]             BIT            NOT NULL,
    [UpdatedDate]        DATETIME2 (3)  NULL,
    [CreatedBy]          NVARCHAR (450) NULL,
    [UpdatedBy]          NVARCHAR (450) NULL,
    [CreatedDate]        DATETIME2 (3)  NOT NULL,
    [UserId]             NVARCHAR (MAX) NULL,
    [IsOnfidoVerify]     BIT            DEFAULT ((0)) NOT NULL,
    [OnfidoChecksResult] NVARCHAR (MAX) NULL,
    [Address]            VARCHAR (255)  NULL,
    [KycFailedCount]     INT            DEFAULT ((0)) NOT NULL,
    [KycManualPass]      BIT            DEFAULT ((0)) NOT NULL,
    [KycManualPassDate]  DATETIME2 (7)  NULL,
    [KycVerifiedDate]    DATETIME2 (7)  NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

