CREATE TABLE [dbo].[Payee] (
    [Id]                        INT            IDENTITY (1, 1) NOT NULL,
    [PayeeType]                 INT            NOT NULL,
    [UserId]                    NVARCHAR (MAX) NULL,
    [TenantId]                  INT            NOT NULL,
    [FirstName]                 VARCHAR (50)   NULL,
    [LastName]                  VARCHAR (50)   NULL,
    [CompanyName]               NVARCHAR (MAX) NULL,
    [TypeOfBusinessEntity]      NVARCHAR (MAX) NULL,
    [CompanyWebsite]            NVARCHAR (MAX) NULL,
    [Email]                     NVARCHAR (MAX) NULL,
    [DOB]                       DATETIME2 (3)  NOT NULL,
    [CountryCode]               VARCHAR (50)   NULL,
    [Address]                   VARCHAR (255)  NULL,
    [City]                      VARCHAR (50)   NULL,
    [PostCode]                  VARCHAR (50)   NULL,
    [MobileNumber]              VARCHAR (50)   NULL,
    [IdType]                    INT            NOT NULL,
    [IdNumber]                  VARCHAR (50)   NULL,
    [IdExpiryDate]              DATETIME2 (3)  NOT NULL,
    [SecurityQuestionId]        INT            NOT NULL,
    [Answer]                    NVARCHAR (MAX) NULL,
    [IssuingCountry]            NVARCHAR (MAX) NULL,
    [CompanyRegistrationNumber] NVARCHAR (MAX) NULL,
    [Status]                    BIT            NOT NULL,
    [CreatedBy]                 NVARCHAR (450) NULL,
    [UpdatedBy]                 NVARCHAR (450) NULL,
    [CreatedDate]               DATETIME2 (3)  NOT NULL,
    [UpdatedDate]               DATETIME2 (3)  NOT NULL,
    [Address2]                  VARCHAR (255)  NULL,
    [JazzCashAccount]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Payee] PRIMARY KEY CLUSTERED ([Id] ASC)
);

