CREATE TABLE [dbo].[SecureTradingPaymentDetail] (
    [Id]                           UNIQUEIDENTIFIER NOT NULL,
    [requestreference]             NVARCHAR (MAX)   NULL,
    [version]                      NVARCHAR (MAX)   NULL,
    [secrand]                      NVARCHAR (MAX)   NULL,
    [transactionstartedtimestamp]  NVARCHAR (MAX)   NULL,
    [livestatus]                   NVARCHAR (MAX)   NULL,
    [issuer]                       NVARCHAR (MAX)   NULL,
    [splitfinalnumber]             NVARCHAR (MAX)   NULL,
    [dccenabled]                   NVARCHAR (MAX)   NULL,
    [settleduedate]                NVARCHAR (MAX)   NULL,
    [errorcode]                    NVARCHAR (MAX)   NULL,
    [baseamount]                   NVARCHAR (MAX)   NULL,
    [tid]                          NVARCHAR (MAX)   NULL,
    [merchantnumber]               NVARCHAR (MAX)   NULL,
    [securityresponsepostcode]     NVARCHAR (MAX)   NULL,
    [transactionreference]         NVARCHAR (MAX)   NULL,
    [merchantname]                 NVARCHAR (MAX)   NULL,
    [paymenttypedescription]       NVARCHAR (MAX)   NULL,
    [orderreference]               NVARCHAR (MAX)   NULL,
    [accounttypedescription]       NVARCHAR (MAX)   NULL,
    [acquirerresponsecode]         NVARCHAR (MAX)   NULL,
    [requesttypedescription]       NVARCHAR (MAX)   NULL,
    [securityresponsesecuritycode] NVARCHAR (MAX)   NULL,
    [currencyiso3a]                NVARCHAR (MAX)   NULL,
    [authcode]                     NVARCHAR (MAX)   NULL,
    [errormessage]                 NVARCHAR (MAX)   NULL,
    [operatorname]                 NVARCHAR (MAX)   NULL,
    [merchantcountryiso2a]         NVARCHAR (MAX)   NULL,
    [maskedpan]                    NVARCHAR (MAX)   NULL,
    [securityresponseaddress]      NVARCHAR (MAX)   NULL,
    [issuercountryiso2a]           NVARCHAR (MAX)   NULL,
    [settlestatus]                 NVARCHAR (MAX)   NULL,
    [TenantId]                     INT              NOT NULL,
    [CreatedDate]                  DATETIME2 (7)    NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)    NOT NULL,
    [CreatedBy]                    NVARCHAR (MAX)   NULL,
    [UpdatedBy]                    NVARCHAR (MAX)   NULL,
    [isRefund]                     BIT              DEFAULT ((0)) NOT NULL,
    [CardDetailId]                 INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SecureTradingPaymentDetail] PRIMARY KEY CLUSTERED ([Id] ASC)
);

