CREATE TABLE [dbo].[Transaction] (
    [TransactionId]            INT              IDENTITY (1, 1) NOT NULL,
    [SupplierId]               INT              NOT NULL,
    [BankId]                   INT              NOT NULL,
    [BankBranchId]             INT              NOT NULL,
    [UserId]                   UNIQUEIDENTIFIER NOT NULL,
    [BeneficiaryId]            INT              NOT NULL,
    [SendAmount]               DECIMAL (18, 2)  NOT NULL,
    [PayoutAmount]             DECIMAL (18, 2)  NOT NULL,
    [PaymentMethodId]          INT              NOT NULL,
    [StateId]                  INT              NOT NULL,
    [TransferFee]              DECIMAL (18, 2)  NOT NULL,
    [GST]                      DECIMAL (18, 2)  NOT NULL,
    [SendCountryId]            INT              NOT NULL,
    [PayoutCountryId]          INT              NOT NULL,
    [ExchangeRate]             DECIMAL (18, 2)  NOT NULL,
    [IsFreePayment]            BIT              NOT NULL,
    [PaymentPurpose]           INT              NOT NULL,
    [SourceOfFund]             INT              NOT NULL,
    [Remark]                   VARCHAR (500)    NULL,
    [TransactionRefNo]         VARCHAR (50)     NULL,
    [TransactionBookingNo]     VARCHAR (50)     NULL,
    [SupplierTxnRefNo]         VARCHAR (50)     NULL,
    [SupplierTxnStatus]        NVARCHAR (MAX)   NULL,
    [Status]                   INT              NOT NULL,
    [UpdatedDate]              DATETIME2 (3)    NULL,
    [CreatedBy]                NVARCHAR (450)   NULL,
    [CreatedDate]              DATETIME2 (3)    NOT NULL,
    [UpdatedBy]                NVARCHAR (450)   NULL,
    [TrasactionType]           INT              DEFAULT ((0)) NOT NULL,
    [SecureTradingReferenceNo] NVARCHAR (MAX)   NULL,
    [PayoutModeId]             INT              DEFAULT ((0)) NOT NULL,
    [CaseId]                   INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED ([TransactionId] ASC)
);

